//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForQuilt.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForQuilt.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard does not contain any image as expected.
        /// </summary>
        internal static string Message_Clipboard_does_not_contain_any_image_as_expected {
            get {
                return ResourceManager.GetString("Message_Clipboard_does_not_contain_any_image_as_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear all from this work table?.
        /// </summary>
        internal static string Message_Do_you_want_to_clear_all_from_this_work_table {
            get {
                return ResourceManager.GetString("Message_Do_you_want_to_clear_all_from_this_work_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension is not supported.
        /// </summary>
        internal static string Message_File_extension_is_not_supported {
            get {
                return ResourceManager.GetString("Message_File_extension_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with license does not exist.
        /// </summary>
        internal static string Message_File_with_license_does_not_exist {
            get {
                return ResourceManager.GetString("Message_File_with_license_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects were not copied.
        /// </summary>
        internal static string Message_Objects_were_not_copied {
            get {
                return ResourceManager.GetString("Message_Objects_were_not_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Title_Add_Open {
            get {
                return ResourceManager.GetString("Title_Add_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add picture from web-camera.
        /// </summary>
        internal static string Title_Add_picture_from_web_camera {
            get {
                return ResourceManager.GetString("Title_Add_picture_from_web_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Title_Cancel {
            get {
                return ResourceManager.GetString("Title_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Title_Clear {
            get {
                return ResourceManager.GetString("Title_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string Title_Clipboard {
            get {
                return ResourceManager.GetString("Title_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Title_Color {
            get {
                return ResourceManager.GetString("Title_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Title_Copy {
            get {
                return ResourceManager.GetString("Title_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Title_Copyright {
            get {
                return ResourceManager.GetString("Title_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Title_Delete {
            get {
                return ResourceManager.GetString("Title_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string Title_Draw {
            get {
                return ResourceManager.GetString("Title_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Title_Edit {
            get {
                return ResourceManager.GetString("Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForQuilt.
        /// </summary>
        internal static string Title_ForQuilt {
            get {
                return ResourceManager.GetString("Title_ForQuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Title_Help {
            get {
                return ResourceManager.GetString("Title_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries used.
        /// </summary>
        internal static string Title_Libraries_used {
            get {
                return ResourceManager.GetString("Title_Libraries_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectShowNET Library.
        /// </summary>
        internal static string Title_Library_DirectShowNET {
            get {
                return ResourceManager.GetString("Title_Library_DirectShowNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string Title_Licenses {
            get {
                return ResourceManager.GetString("Title_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Work Table.
        /// </summary>
        internal static string Title_Main_Work_Table {
            get {
                return ResourceManager.GetString("Title_Main_Work_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Title_No {
            get {
                return ResourceManager.GetString("Title_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Title_Ok {
            get {
                return ResourceManager.GetString("Title_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Title_Order {
            get {
                return ResourceManager.GetString("Title_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Title_Paste {
            get {
                return ResourceManager.GetString("Title_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string Title_Rotate {
            get {
                return ResourceManager.GetString("Title_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Title_Save {
            get {
                return ResourceManager.GetString("Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch Work Table.
        /// </summary>
        internal static string Title_Sketch_Work_Table {
            get {
                return ResourceManager.GetString("Title_Sketch_Work_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string Title_Thickness {
            get {
                return ResourceManager.GetString("Title_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string Title_Timer {
            get {
                return ResourceManager.GetString("Title_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Title_Version {
            get {
                return ResourceManager.GetString("Title_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Title_Yes {
            get {
                return ResourceManager.GetString("Title_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ForQuilt.
        /// </summary>
        internal static string ToolTip_About_ForQuilt {
            get {
                return ResourceManager.GetString("ToolTip_About_ForQuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add captured image to work table.
        /// </summary>
        internal static string ToolTip_Add_captured_image_to_work_table {
            get {
                return ResourceManager.GetString("ToolTip_Add_captured_image_to_work_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to front.
        /// </summary>
        internal static string ToolTip_Bring_to_front {
            get {
                return ResourceManager.GetString("ToolTip_Bring_to_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip Cancel capture.
        /// </summary>
        internal static string ToolTip_Cancel_capture {
            get {
                return ResourceManager.GetString("ToolTip_Cancel_capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel capture from web camera.
        /// </summary>
        internal static string ToolTip_Cancel_capture_from_web_camera {
            get {
                return ResourceManager.GetString("ToolTip_Cancel_capture_from_web_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color of selected drawing.
        /// </summary>
        internal static string ToolTip_Change_color_of_selected_drawing {
            get {
                return ResourceManager.GetString("ToolTip_Change_color_of_selected_drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change thickness of selected drawing.
        /// </summary>
        internal static string ToolTip_Change_thickness_of_selected_drawing {
            get {
                return ResourceManager.GetString("ToolTip_Change_thickness_of_selected_drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        internal static string ToolTip_Clear_all {
            get {
                return ResourceManager.GetString("ToolTip_Clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string ToolTip_Clipboard {
            get {
                return ResourceManager.GetString("ToolTip_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue capture from web-camera.
        /// </summary>
        internal static string ToolTip_Continue_capture_from_web_camera {
            get {
                return ResourceManager.GetString("ToolTip_Continue_capture_from_web_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ToolTip_Copy {
            get {
                return ResourceManager.GetString("ToolTip_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        internal static string ToolTip_Crop {
            get {
                return ResourceManager.GetString("ToolTip_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string ToolTip_Cut {
            get {
                return ResourceManager.GetString("ToolTip_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ToolTip_Delete {
            get {
                return ResourceManager.GetString("ToolTip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string ToolTip_Draw {
            get {
                return ResourceManager.GetString("ToolTip_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw ellipse or circle.
        /// </summary>
        internal static string ToolTip_Draw_ellipse_or_circle {
            get {
                return ResourceManager.GetString("ToolTip_Draw_ellipse_or_circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw line.
        /// </summary>
        internal static string ToolTip_Draw_line {
            get {
                return ResourceManager.GetString("ToolTip_Draw_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw rectangle or square.
        /// </summary>
        internal static string ToolTip_Draw_rectangle_or_square {
            get {
                return ResourceManager.GetString("ToolTip_Draw_rectangle_or_square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing color.
        /// </summary>
        internal static string ToolTip_Drawing_color {
            get {
                return ResourceManager.GetString("ToolTip_Drawing_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing thikness.
        /// </summary>
        internal static string ToolTip_Drawing_thikness {
            get {
                return ResourceManager.GetString("ToolTip_Drawing_thikness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase drawing.
        /// </summary>
        internal static string ToolTip_Erase_drawing {
            get {
                return ResourceManager.GetString("ToolTip_Erase_drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ToolTip_Exit {
            get {
                return ResourceManager.GetString("ToolTip_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selected area as image to file.
        /// </summary>
        internal static string ToolTip_Export_selected_area_as_image_to_file {
            get {
                return ResourceManager.GetString("ToolTip_Export_selected_area_as_image_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export work area as image to file.
        /// </summary>
        internal static string ToolTip_Export_work_area_as_image_to_file {
            get {
                return ResourceManager.GetString("ToolTip_Export_work_area_as_image_to_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group selected drawings.
        /// </summary>
        internal static string ToolTip_Group_selected_drawings {
            get {
                return ResourceManager.GetString("ToolTip_Group_selected_drawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string ToolTip_Help {
            get {
                return ResourceManager.GetString("ToolTip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import image from file.
        /// </summary>
        internal static string ToolTip_Import_image_from_file {
            get {
                return ResourceManager.GetString("ToolTip_Import_image_from_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ToolTip_Paste {
            get {
                return ResourceManager.GetString("ToolTip_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause capture from web-camera.
        /// </summary>
        internal static string ToolTip_Pause_capture_from_web_camera {
            get {
                return ResourceManager.GetString("ToolTip_Pause_capture_from_web_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeate selected drawings or images.
        /// </summary>
        internal static string ToolTip_Repeate_selected_drawings_or_images {
            get {
                return ResourceManager.GetString("ToolTip_Repeate_selected_drawings_or_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset rotation.
        /// </summary>
        internal static string ToolTip_Reset_rotation {
            get {
                return ResourceManager.GetString("ToolTip_Reset_rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string ToolTip_Rotate {
            get {
                return ResourceManager.GetString("ToolTip_Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left on 1 degree.
        /// </summary>
        internal static string ToolTip_Rotate_left_on_1_degree {
            get {
                return ResourceManager.GetString("ToolTip_Rotate_left_on_1_degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left on 45 degree.
        /// </summary>
        internal static string ToolTip_Rotate_left_on_45_degree {
            get {
                return ResourceManager.GetString("ToolTip_Rotate_left_on_45_degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right on 1 degree.
        /// </summary>
        internal static string ToolTip_Rotate_right_on_1_degree {
            get {
                return ResourceManager.GetString("ToolTip_Rotate_right_on_1_degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right on 45 degree.
        /// </summary>
        internal static string ToolTip_Rotate_right_on_45_degree {
            get {
                return ResourceManager.GetString("ToolTip_Rotate_right_on_45_degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate selected objects.
        /// </summary>
        internal static string ToolTip_Rotate_selected_objects {
            get {
                return ResourceManager.GetString("ToolTip_Rotate_selected_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation angle.
        /// </summary>
        internal static string ToolTip_Rotation_angle {
            get {
                return ResourceManager.GetString("ToolTip_Rotation_angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by lasso.
        /// </summary>
        internal static string ToolTip_Select_by_lasso {
            get {
                return ResourceManager.GetString("ToolTip_Select_by_lasso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by rectangle.
        /// </summary>
        internal static string ToolTip_Select_by_rectangle {
            get {
                return ResourceManager.GetString("ToolTip_Select_by_rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to back.
        /// </summary>
        internal static string ToolTip_Send_to_back {
            get {
                return ResourceManager.GetString("ToolTip_Send_to_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show clipboard.
        /// </summary>
        internal static string ToolTip_Show_Clipboard {
            get {
                return ResourceManager.GetString("ToolTip_Show_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer to capture from web camera.
        /// </summary>
        internal static string ToolTip_Timer_to_capture_from_web_camera {
            get {
                return ResourceManager.GetString("ToolTip_Timer_to_capture_from_web_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup selected drawings.
        /// </summary>
        internal static string ToolTip_Ungroup_selected_drawings {
            get {
                return ResourceManager.GetString("ToolTip_Ungroup_selected_drawings", resourceCulture);
            }
        }
    }
}
